run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Blank identifier assignments are intentional for optional error handling
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Field alignment is an optimization, not a correctness issue
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/commjoen/domainintel
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # Audit errors not checked - we handle this with errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: test/
      linters:
        - errcheck
        - gosec
    # Exclude unusedwrite in test files as they are testing struct initialization
    - linters:
        - govet
      text: "unusedwrite:"
  max-issues-per-linter: 0
  max-same-issues: 0
