version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
    gosec:
      excludes:
        - G104
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - path: test/
        linters:
          - errcheck
          - gosec
      - linters:
          - govet
        text: "unusedwrite:"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/commjoen/domainintel

output:
  show-stats: true
